# Generated by Django 5.2.17 on 2026-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('predicted_breed', models.CharField(max_length=120)),
                ('confidence', models.FloatField()),
                ('latency_ms', models.FloatField()),
                ('model_version', models.CharField(default='tf-ensemble-v1', max_length=100)),
            ],
        ),
    ]
